web:
  image: 'gitlab/gitlab-ee:latest'
  restart: always
  hostname: 'gitlab.nilssab.loginto.me'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://gitlab.nilssab.loginto.me'
      gitlab_rails['gitlab_shell_ssh_port'] = 2224
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - '80:80'
    - '443:443'
    - '2224:22'
  volumes:
    - '$GITLAB_HOME/config:/etc/gitlab'
    - '$GITLAB_HOME/logs:/var/log/gitlab'
    - '$GITLAB_HOME/data:/var/opt/gitlab'